### ISSUE TITLE
Round edges blurry or overgrowing?

### ISSUE THREAD

**Issue by donni106** [yanqiw/react-native-icon-badge#13]
Hi, my badges are not very clean. When rendered, they seem blurry. (React Native 0.55.4)

Style:
```
badgeIcon: {
  alignItems: 'center',
  backgroundColor: colors.black,
  borderColor: colors.red,
  borderRadius: 50,
  borderWidth: 1.5,
  height: 20,
  justifyContent: 'center',
  minWidth: 20,
  position: 'absolute',
  right: -12,
  top: -5
}
```

Results:
<img width="350" alt="bildschirmfoto 2019-02-14 um 18 40 00" src="https://user-images.githubusercontent.com/1942953/52806940-88c8ec80-308a-11e9-994e-d7cb481328b7.png">

<img width="352" alt="bildschirmfoto 2019-02-14 um 18 49 54" src="https://user-images.githubusercontent.com/1942953/52807006-aeee8c80-308a-11e9-989f-90da15a615d6.png">

<img width="338" alt="bildschirmfoto 2019-02-14 um 18 50 42" src="https://user-images.githubusercontent.com/1942953/52807012-b2821380-308a-11e9-9ca2-9a2e121491b4.png">

No matter the colors, the border width or border radius, the color pierces the edges.
Is there a way to avoid this?

Comparable styling in the web is rendered like this:
<img width="136" alt="bildschirmfoto 2019-02-14 um 19 05 56" src="https://user-images.githubusercontent.com/1942953/52807407-a8144980-308b-11e9-8979-dd99163d01fe.png">

**Comment by donni106** [comment]
It looks like a bigger React Native issue. I found this issue: https://github.com/facebook/react-native/issues/17267

The problem should be fixed with React Native 0.56.0. I will try this.

**Comment by donni106** [comment]
Hmmm, sadly it is not fixed yet. I updated to 0.56.0.

<img width="307" alt="bildschirmfoto 2019-02-14 um 20 47 52" src="https://user-images.githubusercontent.com/1942953/52813515-3c85a880-309a-11e9-999b-098ecaa40109.png">

Maybe better with 0.56.1.

**Comment by donni106** [comment]
Nope:

<img width="308" alt="bildschirmfoto 2019-02-14 um 20 56 14" src="https://user-images.githubusercontent.com/1942953/52813848-fed54f80-309a-11e9-8018-bfb6539f87b9.png">

Or I forgot something during update.
I will check that tomorrow again.

**Comment by donni106** [comment]
On Android it looks good.

<img width="306" alt="bildschirmfoto 2019-02-15 um 14 45 47" src="https://user-images.githubusercontent.com/1942953/52860701-7d300100-3130-11e9-9e39-a8ba026d7235.png">

(I don't know exactly whether it was bad on Android before)

**Comment by donni106** [comment]
With adding `overflow: 'hidden'` it gets better on iOS, thx to: https://github.com/facebook/react-native/issues/4604#issuecomment-346317843

<img width="270" alt="bildschirmfoto 2019-02-15 um 15 21 24" src="https://user-images.githubusercontent.com/1942953/52862425-8ec7d780-3135-11e9-9d7a-0d290321f87b.png">

**Comment by yanqiw** [comment]
Hi @donni106 ,  thx for resolving this.
