### ISSUE TITLE
How to add Padding

### ISSUE THREAD

**Issue by eyalabadi98** [yanqiw/react-native-icon-badge#4]
Hello, I placed my object on a tab, but the badge is not positioned correctly, it need more padding bottom and left. Where should I place these styles? I tried on MainView, IconBadge and IconBadgeElement, but they are not affecting it correctly.

Please let me know how to fix this! thanks

**Comment by yanqiw** [comment]
hi @eyalabadi98 , the badge uses 'top' and 'right' to control the position.  you can use 'IconBadgeStyle' to overwrite the them.  if you still has the problem, could u put a screenshot and code here.

**Comment by eyalabadi98** [comment]
Hey @yanqiw! I did these changes, but when I changed my ios device to have a bigger or smalle screen, its messed up. Do you have any tips? 

I have tried using flex, but its still messed up as this component  is rendered on top of another one and its absolute

here is my code, if its helps at all
`<IconBadge
            MainElement={
                <View style={{paddingBottom: 0}}>
                    <SegmentedControlTab
                      values={['Upcoming', 'Requests',]}
                      selectedIndex={this.state.selectedIndex}
                      onTabPress={this.handleIndexChange}
                      tabsContainerStyle={styles.tabsContainerStyle}
                    />
                </View>
            }
            //Hidden={this.state.BadgeCount === 0}
            Hidden={false}
            BadgeElement={
              <Text style={{color:'#FFFFFF', paddingLeft: 0}}>{this.state.BadgeCount}</Text>
            }
            IconBadgeStyle={
              {width: 20,
              height: 20,
              //paddingBottom: 6,
              marginLeft: 0,
              opacity: show,
              //bottom: 8,
              //top: -10,
              //left: 181,
              }
            }
            />`

Thank you

**Comment by eyalabadi98** [comment]
@yanqiw any updates?

**Comment by yanqiw** [comment]
Hi @eyalabadi98 
I did a test for your code. I think the problem is the width of 'SegmentedControlTab' is based on screen width which is dynamic, but the badge position is absolute, so when you change the device, your 'SegmentedControlTab' width changed, but the left didn't.  
here are two suggestions:
if ur RN > 0.42, u can use present for the 'left', ext. change the left:181 to left:"45%" 
if ur RN< 0.42, u can set width of ur 'SegmentedControlTab'

**Comment by yanqiw** [comment]
closed for now
