### ISSUE TITLE
How to add marginLeft in IconBadgeStyle.

### ISSUE THREAD

**Issue by Donhv** [yanqiw/react-native-icon-badge#7]
I want add marginLeft in IconBadge Here is my code:
`<IconBadge
                        MainElement={
                            <View style={{
                                backgroundColor: '#489EFE',
                                width: 50,
                                height: 50,
                                margin: 6,
                            }} />
                        }
                        BadgeElement={
                            <Text style={{ color: '#FFFFFF' }}>3</Text>
                        }
                        IconBadgeStyle={
                            {
                                width: 30,
                                height: 30,
                                backgroundColor: '#FF00EE',
                                # marginLeft:100
                            }
                        }
                    />`
But iconBadge not change:
![screen shot 2018-01-22 at 10 10 59 am](https://user-images.githubusercontent.com/16864971/35203815-afd7faec-ff5c-11e7-9b66-4f75588d7aff.png)

Seem my issue just appear which marginLeft because I try change 'marginLeft' to marginRight it work well.
![screen shot 2018-01-22 at 10 09 39 am](https://user-images.githubusercontent.com/16864971/35203814-af9f08b8-ff5c-11e7-9562-abb72bd8dcbd.png)
Pls help me
P/s I want my MainElement not moving and iconBadge moving.

**Comment by Donhv** [comment]
@yanqiw can you help me?

**Comment by yanqiw** [comment]
@Donhv  the position of the icon is 'top/right', so, the marginLeft may don't effect.  i thin you want to move the icon to right, you can try to set 'right: -100' to move it.

**Comment by yanqiw** [comment]
close for long time no response.

**Comment by Donhv** [comment]
@yanqiw sorry. i forget respone. it's work well. thanks u very much <3
